parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  displayName: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: echo running templated job
    displayName: ${{ parameters.displayName }}